<?php

namespace App\Http\Middleware;

use App\Services\User\Active;
use Closure;
use Illuminate\Auth\Middleware\Authenticate as Middleware;

class Authenticate extends Middleware
{
    /**
     * Get the path the user should be redirected to when they are not authenticated.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return string|null
     */
    protected function redirectTo($request)
    {
        if (! $request->expectsJson()) {
            return route('login');
        }
        //Active::setActive();

    }
    // Бу метод керак эмас
    /* public function handle($request, Closure $next, ...$guards)
    {
        if (auth()->check()){
            Active::setActive($request->user());
        }
        return parent::handle($request, $next, $guards); // TODO: Change the autogenerated stub
    } */

}
